### ISSUE TITLE
Add Chapter about LibresSettings (changing Locale dynamic) in README

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [Skeptick/libres#11]
Now we must research the source code, to know how to change Language dynamics. Please, add a section in README (or attach link, where to search).

**Comment by Skeptick** [comment]
Hi. `LibresSettings`, for the most part, is designed for special cases. By default it's suggests using standard methods of changing language in OS (although for iOS will need Method Swizzling to override current locale).
But you're absolutely right, all this should be covered in documentation and perhaps adding a more canonical way for iOS is my backlog. Thank you for highlighting this moment!

**Comment by Skeptick** [comment]
https://github.com/Skeptick/libres/blob/master/docs/LOCALIZATION.md
