### ISSUE TITLE
No image displayed / black image on iOS

### ISSUE THREAD

**Issue by EBfVince** [Skeptick/libres#19]
I just added libres to my Compose Multiplatform project. 

The library works fine on Android, but on iOS, no images are displayed. Instead, I see black images.

I checked in XCode and found the `LibresShared` file with my 2 images inside. So it looks that the images are correctly copied into the iOS project, but they are not displayed correctly in the iOS app.

There is no error message in the console.

Here is the project I'm working on, you can certainly reproduce the bug by running it on iOS:
https://github.com/EBfVince/chatgpt-compose-multiplatform

Don't hesitate to ask me if you need more information.

**Comment by Skeptick** [comment]
Hi. Please see [Images section in README](https://github.com/Skeptick/libres#images). Especially about modifiers and specifically about `orig`. Black images on iOS are normal because UIKit treats them as templates and recolors to default color (usually blue or black).

**Comment by EBfVince** [comment]
Thank you for your reactivity. It works perfectly now 👍
