### ISSUE TITLE
Bug. Ios 15. Application language does not match the system language

### ISSUE THREAD

**Issue by jershell** [Skeptick/libres#22]
Compose application language does not match the system language. 
On IOS 15 `NSLocale.currentLocale.languageCode`always return en. On the version of 16+`NSLocale.currentLocale.languageCode` works right.

**Comment by Skeptick** [comment]
Hi. It's not a bug. `currentLanguage` and `preferredLanguages` (from your PR) have a slightly different role. In order for `currentLanguage` to work correctly it must be added as supported in XCode project (see screenshot)
![Снимок экрана 2023-06-23 в 01 41 32](https://github.com/Skeptick/libres/assets/13118032/32437484-c4c1-448c-b7b1-5a0d8802bb0f)
