### ISSUE TITLE
hi language code is not working in web

### ISSUE THREAD

**Issue by sunildhiman90** [Skeptick/libres#29]
Hi there, Its very easy to start using libres. It has minimal setup procedure. Thanx for that.

But in web, i tried to change the language using LibresSettings.languageCode = "hi"

This is working fine in Android, but in web its not displaying characters,
<img width="672" alt="Screenshot 2023-09-10 at 4 21 41 PM" src="https://github.com/Skeptick/libres/assets/35147222/342bf979-bf2a-49ed-9580-fc18cb57c0bd">

 I think its not able to render characters. i m testing it in latest chrome version.

**Comment by Skeptick** [comment]
Hello. I can't even imagine how this could be related to libres.
Does the text in generated file look normal?
(located in `yourModule/build/generated/libres/common/src/package/strings/StringsHi.kt`)

**Comment by sunildhiman90** [comment]
Yes @Skeptick, if its working fine in android , ios and desktop sides, it means its correct.
<img width="1206" alt="Screenshot 2023-09-17 at 11 20 29 AM" src="https://github.com/Skeptick/libres/assets/35147222/5d3a2e8e-a4e4-41c2-be29-a2b2faa075c0">

but only in web it have issues.
<img width="908" alt="Screenshot 2023-09-17 at 11 23 55 AM" src="https://github.com/Skeptick/libres/assets/35147222/9eb9b9ad-9731-4ac9-b5dd-e554c0b352b6">

**Comment by Skeptick** [comment]
I think that font you're using simply doesn't support your localization. Try changing the font.
