### ISSUE TITLE
Every picture has wrong colours on IOS 17

### ISSUE THREAD

**Issue by Radch-enko** [Skeptick/libres#32]
Tested on "1.2.0-beta01", "1.1.8"
Image type does not matter. 
Image name modifiers: (_orig) are added

On IOS 16.4 everything works fine.

**Comment by VixonneN** [comment]
same problem, and ios doesnot see .svg files

**Comment by anaesthez** [comment]
> same problem, and ios doesnot see .svg files

have same problem now, did you succeed to solve it?

**Comment by VixonneN** [comment]
I have a very small project, I migrated it to moko-resources in 1 day

**Comment by Skeptick** [comment]
Fixed in https://github.com/Skeptick/libres/releases/tag/1.2.0
