### ISSUE TITLE
NoClassDefFound

### ISSUE THREAD

**Issue by InsanusMokrassar** [Skeptick/libres#8]
Using libres withou adding of android plugin and get next error:

`Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/tasks/GenerateResValues`

Is there any way to avoid this problem?

**Comment by Skeptick** [comment]
Hello.
Plugin tries to find this task. I don't think it will be possible to do this without changing the code. I will try to release new version with fix in the near future (1-2 days)

**Comment by InsanusMokrassar** [comment]
It would be awesome, thank you :)
